### ISSUE TITLE
I would like to sponsor your project

### ISSUE THREAD

**Issue by inetshell** [andeman/opn-cli#20]
Hello @andeman! I was looking for an opnsense automation tool found your repo, it looks really good!

Are you interested in extending its functionality? I would like to sponsor you.

The features I'm most interested in are:
- Manage OpenVPN server, client and client specific overrides
- Manage opnsense users (Create user, update password, manage group membership)
- Manage IPsec tunnels
- Manage static routes
- Manage syslog and prometheus node exporter settings

**Comment by tzelch** [comment]
I'd be happy to pitch in as well, these are pretty much the same features that i'm missing too. :)

**Comment by tzelch** [comment]
Hi Andreas!
I just saw you're from Munich too, small world :)

These featuresets would be the most important for me:
- Manage OpenVPN server, client and client specific overrides
- Manage opnsense users (Create user, update password, manage group membership)

I have a migration coming up where this would save me a lot of manual work.
Regards,
Thomas

**Comment by inetshell** [comment]
Thanks for your efforts @andeman !

**Comment by inetshell** [comment]
> These featuresets would be the most important for me:
> 
>     * Manage OpenVPN server, client and client specific overrides
> 
>     * Manage opnsense users (Create user, update password, manage group membership)

I agree on prioritizing those features 👍

**Comment by andeman** [comment]
Hey @inetshell @tzelch,

first of all I would like to thank you for your sponsorship. This gives me the motivation to keep improving the automation of OPNsense.

I have news regarding your prioritized features:

Both of the two features (openvpn and user/group management) are currently legacy code in OPNsense. So there is no API available. Means there is no clean and stable way to implement this features.

To realize these features, i have to speak to the OPNSense Team Members first for guidance. I think it´s necessary to migrate these features first to the Phalcon php framework. So there is a stable api available and then add the feature in opn-cli and puppet-opnsense.

i would suggest the following:

Build the following features first:

Manage IPsec tunnels
Manage static routes
Manage syslog and prometheus node exporter settings

as these are straight forward.

Meanwhile i get advise from the OPNsense Team how i can realize these features.

What do you think?

**Comment by inetshell** [comment]
I'm okay with that, how about you @tzelch ?
Thanks in advance

**Comment by tzelch** [comment]
sorry for the late answer.
I'm happy with your suggestion, I like that you try to implement it the right way together with the opnsense team.

**Comment by andeman** [comment]
Closing this issue.

The following Roadmap is planned:

- Manage IPsec tunnels 
- Manage static routes
- Manage syslog and prometheus node exporter settings
- Get advise from the OPNsense Team how to realize OPNsense User and OpenVPN Management via API calls
