### ISSUE TITLE
XDG_CONFIG_HOME Support

### ISSUE THREAD

**Issue by ProfessorManhattan** [andeman/opn-cli#49]
Can you add support for XDG_CONFIG_HOME? Ideally, I'd like to store the configuration at `~/.config/opn-cli/config.yml` if the `XDG_CONFIG_HOME` variable is set.

**Comment by andeman** [comment]
Hi ProfessorManhattan,

thanks for the feedback. 

XDG_CONFIG_HOME is coming in the next days.

**Comment by andeman** [comment]
added in https://github.com/andeman/opn-cli/pull/50
